FROM public.ecr.aws/lambda/python:3.11

# Copiar requirements primero para aprovechar cache de Docker
COPY requirements.txt ${LAMBDA_TASK_ROOT}/

# Instalar dependencias
RUN pip install --default-timeout=300 --no-cache-dir -r requirements.txt

# Copiar código de la aplicación
COPY app ${LAMBDA_TASK_ROOT}/app
COPY main.py ${LAMBDA_TASK_ROOT}/
COPY lambda_handler.py ${LAMBDA_TASK_ROOT}/

CMD ["lambda_handler.handler"]
